### ISSUE TITLE
Look into gpsbabel

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsdio#101]
At least for more info about the ecosystem.  Might also be useful for testing or validating libais.

http://www.gpsbabel.org/htmldoc-development/fmt_nmea.html

**Comment by schwehr** [comment]
Robert Lipe works at Google if there are any gpsbabel questions, I can talk to him.

**Comment by schwehr** [comment]
I just chatted with Robert.  gpsbabel knowns nothing of AIS.  He hadn't heard of it before.  gpsbabel does know tons of gps formats.  Were you thinking about comparing the json output format of gpsd with with the formats supported in gpsbabel?

**Comment by geowurster** [comment]
@schwehr This was more a note so I wouldn't forget, but it [looks like](http://www.gpsbabel.org/capabilities.html) gpsbabel parses NMEA sentences.  It's also listed on the [formats page](http://www.gpsbabel.org/capabilities.html).  I just tried a quick test and couldn't get it to write any data but [this tutorial](http://www.oceandatarat.org/?p=141) mentions that gpsbabel can only read NMEA that is NMEA0183 GGA formatted.

**Comment by robertlipe** [comment]
GPSBabel guy here.   libais seems to be in a largely different space than GPSBabel.  (OK, they're both location-y) I've shipped tens to hundreds of millions of copies and spoken with thousands of users and Kurt's request was the first time I'd heard of AIS. If there's some opportunity to collaborate, great, but this seems extremely specialized and a forced fit.

GPSBabel does read and write a subset of reverse-engineered NMEA - the subset generally used by consumer grade loggers and handheld GPSes.    We don't pretend to handle everything representable by NMEA.  If you're into such things, the responsible code is https://code.google.com/p/gpsbabel/source/browse/trunk/gpsbabel/nmea.cc

I have kicked around the idea of adding GeoJSON or other JSON-based formats.

As to the cited article, yes, GPSBabel requires generally sensible input.  If a GPS marks a trackpoint as 'not valid', we don't use it.  If your program puts junk in front of the NMEA sentences, they aren't NMEA sentences any more.  If you blindly whack sentences containing key data, it will act funny.  (Hint: he should have been using our simplify filter http://www.gpsbabel.org/htmldoc-1.5.2/filter_simplify.html  to decimate his polylines to not overrun Earth.)

**Comment by geowurster** [comment]
@robertlipe Thanks for the clarification!

GPSBabel and libais definitely exist in different spaces but when I saw mention of NMEA on the GPSBabel website I thought it might be worth looking into the functionality to see if it would be useful to us for validation, or even to better understand how other parsers handle different message types.  I definitely was not suggesting that GPSBabel should do more with AIS - that's why we have libais.  If we end up getting data from the loggers you described, then GPSBabel could be a valuable tool but for the foreseeable future we will be working only with AIS.
