### ISSUE TITLE
Switch to logging instead of printing errors to sys.stderr

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsdio#12]

**Comment by redhog** [comment]
This is mainly for validate.collect_info(). I wonder if maybe we should just have a message_error_callback instead? That one could take a more elaborate set of parameters than just a string, like the __invalid__ message substructure...

**Comment by geowurster** [comment]
That could be useful.  I assume you're trying to prevent one line in the log for every error encountered?

**Comment by redhog** [comment]
That, and also using logging or a file doesn't make it very easy to use the information programatically

**Comment by geowurster** [comment]
That's true but if the user wants to be sure they're working with clean data they can use the functions from #5.  I see logging as being more useful overall for debugging pipelines.

**Comment by geowurster** [comment]
Completed over the past few weeks.
