### ISSUE TITLE
Examine the need for having non-gpsd fields in the schema

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsdio#22]
@redhog There are some fields in the schema that are Benthos/libais specific.  We need to figure out the best way for handling these while keeping this library within the GPSD scope.

**Comment by redhog** [comment]
Maybe we could have all extensions have a prefix per extension, like libais_ or tagblock_, and coordinate them with @eric-s-raymond ? Imho it all depends on if Eric is interested in standardizing such extensions or not.

**Comment by redhog** [comment]
I just realized that a very neat way to handle this would be to allow plugins to register new fields (and add them to message types) similarly to how drivers are registered.

**Comment by geowurster** [comment]
That's worth exploring but could cause problems if one plugin modifies the schema in a way that breaks another plugin.

**Comment by redhog** [comment]
Maybe add the plugins name as field prefix by default to minimize clashes? Versioning of schemas is another problem I think...

**Comment by geowurster** [comment]
Closing in favor of #112.
