### ISSUE TITLE
Python 2 vs. 3 support

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsdio#23]
- [ ] Msgpack driver does not work out of the box in Python3

**Comment by schwehr** [comment]
I setup msgpack for python 2.7 and python 3.4 in fink and both appear to work.  What exactly are you seeing for failures?  Or do you mean the code in gpsd_format?

**Comment by geowurster** [comment]
The GPSD MsgPack driver not MsgPack itself.
