### ISSUE TITLE
python setup.py test

### ISSUE THREAD

**Issue by schwehr** [SkyTruth/gpsdio#32]
```python setup.py test```

Should run the tests.  But this is low priority

**Comment by geowurster** [comment]
You can do it [with nosetests](https://github.com/SkyTruth/gpsd_format#developing) right now.

**Comment by geowurster** [comment]
@schwehr done in https://github.com/SkyTruth/gpsdio/commit/4ae7d47deb2d7a107cbaf5d0e159e703c6ed8e25

Until we fix the `test_compatibiltiy` stuff you will have to run with `nosetests -I test_compatibility`.
