### ISSUE TITLE
gpsd builds even when gpsdecode is in the path.

### ISSUE THREAD

**Issue by schwehr** [SkyTruth/gpsdio#35]
```test_aisdecode_known_types (tests.test_compatibility.TestGpsdCompatibility) ... ```

snooze while who knows what is going on in the background

**Comment by redhog** [comment]
Yep, this is to always test against latest version...

**Comment by schwehr** [comment]
Except, I don't want it to do that.  I have my own custom build of gpsd which is 3.14 + cherry picked my patch or git head.  I use the custom version internally and I can't build an executable on the fly in our locked down test env.

patch:  http://git.savannah.gnu.org/cgit/gpsd.git/commit/packet.c?id=5967ffaffa6d1abf7d9b22f06bb8d7dbf71d7624

**Comment by schwehr** [comment]
@redhog I give you points for creative use of a python test env to build a whole C package.

**Comment by redhog** [comment]
Hm. Then I guess we should have multiple tests that does different things, and selectively enable/disable them (with nosetests -I)...

I'm so sneaky :P

I even get the web page listing versions for download and grep out the latests with a regexp. *evil grin*

**Comment by schwehr** [comment]
I would suggest having building gpsd be something you need to explicitly enable if gpsdecode is in the path.
