### ISSUE TITLE
PEP8 __docstring__ and Python3 cleanup

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsdio#4]
- [x] PEP8
- [x] Docstring
- [x] Python3

**Comment by redhog** [comment]
Note: Don't add docstrings to tests, as that renames the tests, so that finding the test function from the nosetests output gets hard. Use comments instead for this special case,

**Comment by geowurster** [comment]
Yeah I figured that out with some of the Benthos tests.

**Comment by geowurster** [comment]
Finished a while ago.
