### ISSUE TITLE
Robust filtering

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsdio#44]
There are a lot of places where filtering could/should happen but the actual filtering mechanism only needs to be implemented once.  A generator that can be attached to a stream and accept an expression for eval is one solution.  Be sure to [properly limit the scope](https://github.com/geowurster/pyin/blob/re-org/pyin/cli.py#L41-L45).

```python
def filter(stream, expression):
    for item in stream:
        if eval(expression, clean_globals, item):
            yield item
```

**Comment by redhog** [comment]
This needs to be available on the command line too.

Pattern this after the filtersplit command prototype we already have in another project.

Important things to note:

* The filter expression needs the message attributes as variables to be able to do e.g. "speed > 5", but also needs the whole message as a dictionary to be able to do e.g. "'latitude' in msg" or "msg.get('speed', 0)"
* The filter expression needs a global environment. In the API this can be a dictionary, but in the command line interface this has to be a set of statements (so the user can do "import lib; x = lib.Foo()" and later in the filter expression "x.bar(msg['speed'])"
* It is in practice very useful to have change functionality available in the same tool. A simple API for this is a dictionary of new column names mapped to expressions to eval in the same environment as the filter expression. These will generate new column values before the filter expression is run.
