### ISSUE TITLE
Basic CLI commands

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/gpsdio#49]
See the [CLI roadmap](https://github.com/SkyTruth/gpsdio/wiki/Commandline-Utility-Roadmap) for more info.

- [x] cat
- [x] load
- [x] insp
- [x] env
- [x] etl with translation, filtering, and sorting

**Comment by redhog** [comment]
What does cat do? To what format? I think it would be more logical with two groups: "import" and "export", with subcommands like json, csv etc.

But: SHouldn't all this be implemented as plugins in other packages?

**Comment by geowurster** [comment]
It dumps to newline JSON.  No groups this time - lets keep it flat.  Basic ETL functionality that doesn't require any difficult dependencies should come packaged with `gpsdio`.  The other stuff will be plugins.  https://github.com/SkyTruth/gpsdio/wiki/Commandline-Utility-Roadmap#goal-1

**Comment by redhog** [comment]
Then I think it should be called tojson, not cat. Cat does not imply any particular format.

**Comment by geowurster** [comment]
`cat` is an established unix command that dumps the contents of a file to stdout.  There will be a note in the `--help` about what format it dumps to and its not dumping to some weird CLI specific format - its using the same format that the entire library uses internally.

**Comment by redhog** [comment]
cat in unix does NOT change the data at all. a cat command that transforms the data is very unintuitive.

A more reasonable comparison would be with the GNU utility recode, or convert.

**Comment by redhog** [comment]
Also, what would "insp" do?

**Comment by geowurster** [comment]
Everybody knows what cat does and its not replacing a general purpose conversion/ETL tool.  I have wished I had it enough times to just add it.

`insp` is analogous to booting up a python interpreter and doing:

```python
import gpsdio
with gpsdio.open(infile) as stream:
    ...
```

It's really useful for debugging and data exploration.
